### ISSUE TITLE
Repository is empty.

### ISSUE THREAD

**Issue by kirkbushell** [bencorlett/laracon-eu-2014#1]
Steps to repeat:
1. Go to: https://github.com/bencorlett/laracon-eu-2014
2. See that repository is empty.

Possible fixes:
1. Write the code
2. Commit code
3. Push to repository

**Comment by bencorlett** [comment]
<3

Sent from my iPhone

Please excuse my brevity

**Comment by kirkbushell** [comment]
Repository is still empty. Zomg man, pick yourself up fool!

**Comment by andreoav** [comment]
:+1:

**Comment by summerblue** [comment]
:+1:

**Comment by bencorlett** [comment]
Lol. I haven’t had time to look at this. Will spin up an app as soon as I have a spare day or two.

**Comment by JavierMartinz** [comment]
:+1:

**Comment by MartijnThomas** [comment]
@bencorlett Can we expect this repo to get up or are you to busy haha ;)

**Comment by k1ng440** [comment]
its been few months. still not up :-1: . Please dont promise people if you cant keep it.

**Comment by bencorlett** [comment]
Truth be told I have forgotten all about it. Will do it, maybe, soon. I have other more pressing matters. 

Sent from my iPhone

Please excuse my brevity

**Comment by bencorlett** [comment]
I was waiting primarily for homestead to include elastic search, then it fell off my radar. If I get some downtime over Christmas I will look to put up some sample code then. @k1ng440, I'm sorry if this freebie not being around has inconvenienced you

**Comment by bencorlett** [comment]
https://github.com/bencorlett/laracon-eu-2014/blob/master/README.md
