### ISSUE TITLE
ElasticSearch Result in Laravel

### ISSUE THREAD

**Issue by symbios-zi** [bencorlett/laracon-eu-2014#2]
Hello @bencorlett 

I have watched your speech at Laracon about ElasticSearch. Now I am trying to configure it to use in my project.

I have a question about results of seaching. 

For example: There is a Model orders, which was indexed I have found some results.  Now I have to show it at my table in admin panel. In simple mode without searching I am getting data from model, but when I searched orders I have to show it in the same table. So what is the best way to retrieve data. 

1. Get data from elastic search and hydrate it to collection of model
2. Get IDs from search result and make query to Order model to get orders by primary IDs
3. Your solution? 

Thank you.

**Comment by bencorlett** [comment]
Hi Anton, thanks for the question :)

Generally speaking, I use approach 2 there.

Approach 1 could be a performance improvement, but only once we're talking thousands and thousands of records, and even then I would assume that the UI/JavaScript might be a little laggy.

I've never had an issue with searching ES, grabbing IDs and doing an `where id in (?)` query :)

Let me know if you have any other questions, or if this helps, just close the issue away when you're ready.

**Comment by symbios-zi** [comment]
@bencorlett thank you. I see. I made like you, coz it seems more comfortable to me.
